#!/usr/bin/env python

import sys
with open(sys.argv[1]) as h:
     h.__next__()
     for line in h:
        fields = line.strip().split('\t')
        for term in fields[2].split(', '):
             print(fields[0], fields[2], sep='\t')

